# Proyecto Práctica 2 - Sesión 3

# Para Ejercicio 2
medirTyContar: medirTyContar.c algoritmos.o 
	gcc -g medirTyContar.c algoritmos.o -o medirTyContar


algoritmos.o: algoritmos.c algoritmos.h
	gcc -c -g algoritmos.c


clean:
	rm *.o


