# PRUEBA ORDENACION

prueba_ordenacion: prueba_ordenacion.c ordenacion.o
	gcc -g prueba_ordenacion.c ordenacion.o -o prueba_ordenacion
ordenacion.o: ordenacion.c ordenacion.h
	gcc -c -g ordenacion.c

# Varios
clean:
	rm *.o

